In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("EDGAR 3.5 JLU Giessen (1).csv", encoding='utf-8')
df.describe()
df.shape[1]

52

In [15]:
df.describe()

,ALL_Acidovorax_carolinensis_strain_NA2_NZ_CP021359,Acidovorax_carolinensis_strain_NA2_NZ_CP021359,Acidovorax_carolinensis_strain_NA2_plasmid_pACNA2_1_NZ_CP021360,ALL_Acidovorax_carolinensis_strain_P3_NZ_CP021362,Acidovorax_carolinensis_strain_P3_NZ_CP021362,Acidovorax_carolinensis_strain_P3_plasmid_pACP3_3_NZ_CP021365,Acidovorax_carolinensis_strain_P3_plasmid_pACP3_1_NZ_CP021363,Acidovorax_carolinensis_strain_P3_plasmid_pACP3_2_NZ_CP021364,ALL_Acidovorax_carolinensis_strain_P4_NZ_CP021366,Acidovorax_carolinensis_strain_P4_plasmid_pACP4_1_NZ_CP021367,...,Acidovorax_avenae_subsp_avenae_strain_Sa2_CP028301,Acidovorax_carolinensis_strain_NA3_chromosome_1_NZ_CP021361,Acidovorax_cattleyae_strain_CAT98_1_NZ_CP028290,Acidovorax_citrulli_AAC00_1_NC_008752,Acidovorax_citrulli_strain_KACC17005_NZ_CP023687,Acidovorax_ebreus_TPSY_NC_011992,Acidovorax_sp_1608163_NZ_CP033069,Acidovorax_sp_HDW3_NZ_CP049885,Acidovorax_sp_KKS102_NC_018708,Acidovorax_sp_RAC01_NZ_CP016447
count,14551,14551,14551,14551,14551,14551,14551,14551,14551,14551,...,14551,14551,14551,14551,14551,14551,14551,14551,14551,14551
unique,3646,3584,63,3643,3218,89,257,122,4117,263,...,3317,3419,3768,4636,4505,3454,4180,2815,4652,3906
top,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -"
freq,10906,10968,14488,10878,11301,14457,14289,14417,10414,14284,...,11022,11087,10616,9712,9851,10932,10249,11620,9715,10512

In [ ]:
df = df.replace("- , -", " ")

,ALL_Acidovorax_carolinensis_strain_NA2_NZ_CP021359,Acidovorax_carolinensis_strain_NA2_NZ_CP021359,Acidovorax_carolinensis_strain_NA2_plasmid_pACNA2_1_NZ_CP021360,ALL_Acidovorax_carolinensis_strain_P3_NZ_CP021362,Acidovorax_carolinensis_strain_P3_NZ_CP021362,Acidovorax_carolinensis_strain_P3_plasmid_pACP3_3_NZ_CP021365,Acidovorax_carolinensis_strain_P3_plasmid_pACP3_1_NZ_CP021363,Acidovorax_carolinensis_strain_P3_plasmid_pACP3_2_NZ_CP021364,ALL_Acidovorax_carolinensis_strain_P4_NZ_CP021366,Acidovorax_carolinensis_strain_P4_plasmid_pACP4_1_NZ_CP021367,...,Acidovorax_avenae_subsp_avenae_strain_Sa2_CP028301,Acidovorax_carolinensis_strain_NA3_chromosome_1_NZ_CP021361,Acidovorax_cattleyae_strain_CAT98_1_NZ_CP028290,Acidovorax_citrulli_AAC00_1_NC_008752,Acidovorax_citrulli_strain_KACC17005_NZ_CP023687,Acidovorax_ebreus_TPSY_NC_011992,Acidovorax_sp_1608163_NZ_CP033069,Acidovorax_sp_HDW3_NZ_CP049885,Acidovorax_sp_KKS102_NC_018708,Acidovorax_sp_RAC01_NZ_CP016447
0,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -"
1,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -"
2,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -"
3,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -"
4,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14546,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","BSY15_RS20300, ,psos,redoxin domain-containing..."
14547,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","BSY15_RS20310, ,psos,xanthine dehydrogenase fa..."
14548,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","BSY15_RS20315, ,psos,helix-turn-helix transcri..."
14549,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","BSY15_RS20340, ,psos,GNAT family N-acetyltrans..."
14550,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -",...,"- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","- , -","BSY15_RS20345, ,psos,ABC transporter ATP-bindi..."