In [81]:
import pandas as pd
import openpyxl

In [82]:
df = pd.read_csv("EDGAR 3.5 JLU Giessen (1).csv", encoding='utf-8')
print(len(df.columns))
df = df.replace(' - , -' , '-,-,-') 

df = df.loc[:, ~df.columns.str.contains('plasmid', case=False)]
for col in df.columns:
    df[col]=df[col].str.replace(', ,', ',')

df.head(100)

52

,ALL_Acidovorax_carolinensis_strain_NA2_NZ_CP021359,Acidovorax_carolinensis_strain_NA2_NZ_CP021359,ALL_Acidovorax_carolinensis_strain_P3_NZ_CP021362,Acidovorax_carolinensis_strain_P3_NZ_CP021362,ALL_Acidovorax_carolinensis_strain_P4_NZ_CP021366,Acidovorax_carolinensis_strain_P4_NZ_CP021366,ALL_Acidovorax_citrulli_strain_M6_NZ_CP029373,Acidovorax_citrulli_strain_M6_NZ_CP029373,ALL_Acidovorax_sp_JS42_NC_008782,Acidovorax_sp_JS42_NC_008782,...,Acidovorax_avenae_subsp_avenae_strain_Sa2_CP028301,Acidovorax_carolinensis_strain_NA3_chromosome_1_NZ_CP021361,Acidovorax_cattleyae_strain_CAT98_1_NZ_CP028290,Acidovorax_citrulli_AAC00_1_NC_008752,Acidovorax_citrulli_strain_KACC17005_NZ_CP023687,Acidovorax_ebreus_TPSY_NC_011992,Acidovorax_sp_1608163_NZ_CP033069,Acidovorax_sp_HDW3_NZ_CP049885,Acidovorax_sp_KKS102_NC_018708,Acidovorax_sp_RAC01_NZ_CP016447
0,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","AJS_RS00215,psos,IS630 family transposase,IDEN...","AJS_RS00215,psos,IS630 family transposase,IDEN...",...,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-"
1,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","AJS_RS00980,psos,N-6 DNA methylase","AJS_RS00980,psos,N-6 DNA methylase",...,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-"
2,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","AJS_RS00985,psos,DNA damage-inducible protein D","AJS_RS00985,psos,DNA damage-inducible protein D",...,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-"
3,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","AJS_RS00990,psos,type III restriction endonucl...","AJS_RS00990,psos,type III restriction endonucl...",...,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-"
4,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","AJS_RS00995,psos,restriction endonuclease","AJS_RS00995,psos,restriction endonuclease",...,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-",...,"C8235_00260,psos,taurine ABC transporter subst...","-,-,-","C8240_RS00240,psos,taurine ABC transporter sub...","-,-,-","-,-,-","-,-,-","EAG14_RS04165,psos,taurine ABC transporter sub...","-,-,-","-,-,-","-,-,-"
96,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-",...,"C8235_00550,psos,SRPBCC family protein","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-"
97,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","APS58_RS00800,psos,stress-induced protein","APS58_RS00800,psos,stress-induced protein","AJS_RS01665,psos,stress-induced protein","AJS_RS01665,psos,stress-induced protein",...,"-,-,-","-,-,-","C8240_RS12720,psos,stress-induced protein","AAVE_RS12035,psos,stress-induced protein","CQB05_RS02480,psos,stress-induced protein","DTPSY_RS01585,psos,stress-induced protein","-,-,-","-,-,-","-,-,-","BSY15_RS10945,psos,hypothetical protein"
98,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-",...,"C8235_06640,psos,IS5/IS1182 family transposase","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","EAG14_RS01120,psos,IS5 family transposase,IDEN...","-,-,-","-,-,-","-,-,-"
99,"-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","-,-,-","APS58_RS02080,psos,tripartite tricarboxylate t...","APS58_RS02080,psos,tripartite tricarboxylate t...","-,-,-","-,-,-",...,"C8235_10665,psos,ABC transporter substrate-bin...","-,-,-","C8240_RS14930,psos,tripartite tricarboxylate t...","AAVE_RS09605,psos,tripartite tricarboxylate tr...","CQB05_RS04985,psos,tripartite tricarboxylate t...","-,-,-","EAG14_RS18410,psos,tripartite tricarboxylate t...","-,-,-","C380_RS03475,psos,tripartite tricarboxylate tr...","-,-,-"

In [84]:
df = df.applymap(lambda x: x.split(',')[0] if isinstance(x, str) else x)
df.replace('-', pd.NA, inplace=True)
df.to_csv("cleaned_EDGAR.csv", index=False)
df

C:\Users\amgot\AppData\Local\Temp\ipykernel_5248\2661362234.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.split(',')[0] if isinstance(x, str) else x)

,ALL_Acidovorax_carolinensis_strain_NA2_NZ_CP021359,Acidovorax_carolinensis_strain_NA2_NZ_CP021359,ALL_Acidovorax_carolinensis_strain_P3_NZ_CP021362,Acidovorax_carolinensis_strain_P3_NZ_CP021362,ALL_Acidovorax_carolinensis_strain_P4_NZ_CP021366,Acidovorax_carolinensis_strain_P4_NZ_CP021366,ALL_Acidovorax_citrulli_strain_M6_NZ_CP029373,Acidovorax_citrulli_strain_M6_NZ_CP029373,ALL_Acidovorax_sp_JS42_NC_008782,Acidovorax_sp_JS42_NC_008782,...,Acidovorax_avenae_subsp_avenae_strain_Sa2_CP028301,Acidovorax_carolinensis_strain_NA3_chromosome_1_NZ_CP021361,Acidovorax_cattleyae_strain_CAT98_1_NZ_CP028290,Acidovorax_citrulli_AAC00_1_NC_008752,Acidovorax_citrulli_strain_KACC17005_NZ_CP023687,Acidovorax_ebreus_TPSY_NC_011992,Acidovorax_sp_1608163_NZ_CP033069,Acidovorax_sp_HDW3_NZ_CP049885,Acidovorax_sp_KKS102_NC_018708,Acidovorax_sp_RAC01_NZ_CP016447
0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,AJS_RS00215,AJS_RS00215,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,AJS_RS00980,AJS_RS00980,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,AJS_RS00985,AJS_RS00985,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,AJS_RS00990,AJS_RS00990,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,AJS_RS00995,AJS_RS00995,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14546,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,BSY15_RS20300
14547,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,BSY15_RS20310
14548,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,BSY15_RS20315
14549,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,BSY15_RS20340
14550,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,BSY15_RS20345

In [85]:
# Collect unique non-null gene names per strain (column)
unique_genes = df.apply(lambda col: list(col.dropna().unique()))

# Convert to JS object
js_map = "const geneCounts = {\n"
for strain, genes in unique_genes.items():
    gene_list = ', '.join(f'"{gene}"' for gene in genes)
    js_map += f'  "{strain}": [{gene_list}],\n'
js_map += "};"

# Save to JS file
with open("gene_counts.js", "w") as f:
    f.write(js_map)